
    
      const data = [
        {
          "Id": 1,
          "name": "Alphonso Mango",
          "imgurl1": "https://i.postimg.cc/qB3f0LyW/2.jpg",
          "imgurl2": "https://i.postimg.cc/qB3f0LyW/2.jpg",
          "stock": "In Stock",
          "introduction": "The Alphonso mango, named after Afonso de Albuquerque, a prominent Portuguese viceroy, is renowned for its superior taste and quality. Jesuit missionaries introduced grafting techniques in Portuguese Goa, creating this esteemed variety. Mentioned by Garcia da Orta in 1563, Alphonso mangoes from Portuguese Bombay were presented to the Goa viceroy. Known for their exceptional sweetness and creamy texture, Alphonso mangoes are among the most expensive varieties. They are primarily cultivated in the Konkan region of Maharashtra in Western India, celebrated for their rich flavor and high demand both domestically and internationally.",
          "description": "The Alphonso mango variety is named after Afonso de Albuquerque, a distinguished military leader and viceroy of Portuguese India from 1509 to 1515. Jesuit missionaries introduced grafting techniques on mango trees in Portuguese Goa, leading to the production of superior varieties like Alphonso.In 1563, Garcia da Orta, a Portuguese physician and botanist, mentioned Alphonso mangoes grown in Portuguese Bombay (now Mumbai). These mangoes were often presented as gifts to the governor (viceroy) in Goa.Alphonso mangoes are renowned for their exceptional sweetness, rich flavor, and creamy texture, making them one of the most expensive mango varieties. They are primarily grown in the Konkan region of Maharashtra in Western India.",
          "Packaging": "1 Box Containing 5 KG Of Mangoes",
          "Package": "Box",
          "Quantity": 1,
          "Product Form": "Tablet",
          "MRP": 500,
          "discount_percent": "Get 20% OFF",
          "bought": "3,601 people bought this recently",
          "storage": "Store below 30C",
          "country_of_origin": "India",
          "for_sale": "ADD TO CART",
        },
        {
          "Id": 2,
          "name": "Banganapalle Mango",
          "imgurl1": "https://i.postimg.cc/Z5JX8z2h/3.jpg",
          "imgurl2": "https://i.postimg.cc/Z5JX8z2h/3.jpg",
          "stock": "In Stock",
          "introduction": "The Banganapalle mango, also known as Benishan and Bernisha, originates from Banganapalle in Andhra Pradesh, India, occupying 70% of the state’s mango cultivation area. Registered as a geographical indication on May 3, 2017, this variety is also grown in other parts of India and Pakistan. The mango is obliquely oval, about 20 cm long, with yellow flesh and a thin, smooth yellow skin. It has a firm, sweet, fiberless texture, making it highly sought after. As a late-season variety, it is excellent for canning and is rich in vitamins A and C, often called the King of Mangoes.",
          "description": "The Banganapalle mango, also known as Benishan and Bernisha, is a popular mango variety originating from Banganapalle in the Nandyal District of Andhra Pradesh, India. This variety is significant as it occupies 70% of the total mango cultivable area in the state and was initially introduced by farmers from Banaganapalli. On May 3, 2017, it was registered as a geographical indication (GI) from Andhra Pradesh under horticultural products by the Geographical Indication Registry.The Banganapalle mango is also cultivated in other parts of India and Pakistan. The fruit is characterized by its obliquely oval shape, approximately 20 cm in length, with yellow flesh and a thin, smooth yellow skin. The flesh has a firm, meaty texture, is sweet, and lacks fiber, making it highly desirable. This cultivar is especially sought after in Andhra Pradesh and is known for being a very late-season variety, which makes it ideal for canning. Additionally, the Banganapalle mango is a rich source of vitamins A and C and is often referred to as the King of Mangoes.",
          "Packaging": "1 Box Containing 5 KG Of Mangoes",
          "Package": "Strip",
          "Quantity": 1,
          "Product Form": "Tablet",
          "MRP": 300,
          "discount_percent": "Get 20% OFF",
          "bought": "3,601 people bought this recently",
          "storage": "Store below 30C",
          "country_of_origin": "India",
          "for_sale": "ADD TO CART",
          
        },
        {
          "Id": 3,
          "name": "Neelum Mango",
          "imgurl1": "https://i.postimg.cc/kgwzwhPR/4.jpg",
          "imgurl2": "https://i.postimg.cc/kgwzwhPR/4.jpg",
          "stock": "In Stock",
          "introduction": "Neelum mangoes are a commercial variety of mango that are native to Tamil Nadu and are primarily grown in Karnataka, Andhra Pradesh, and Tamil Nadu. They are known for their shape, taste, and floral aroma, and are a late season variety.",
          "description": "Neelum mangoes can be eaten fresh, sliced, or cubed in salads, smoothies, or desserts. Because their firm flesh holds its shape well, they are ideal for transporting long distances and have good keeping quality. To ripen, harvest the fruit when it's mature green and allow it to ripen at room temperature off the tree.",
          "Packaging":"1 Box Containing 5 KG Of Mangoes",
          "Package": "Strip",
          "Quantity": 1,
          "Product Form": "Tablet",
          "MRP": 350,
          "discount_percent": "Get 20% OFF",
          "bought": "3,601 people bought this recently",
          "storage": "Store below 30C",
          "country_of_origin": "India",
          "for_sale": "ADD TO CART",
          
        },
        {
          "Id": 4,
          "name": "Badami Mango",
          "imgurl1": "https://i.postimg.cc/XJtTdGS2/5.jpg",
          "imgurl2": "https://i.postimg.cc/XJtTdGS2/5.jpg",
          "stock": "In Stock",
          "introduction": "Badami mangoes, also known as Karnataka Alphonso, are a variety of mango grown in India. They are known for their sweet taste, creamy texture, and smooth, velvety flesh. Badami mangoes are small to medium in size, with pale yellow skin and attractive yellow or orange flesh. They are also rich in vitamins A and C, as well as iron, folate, and magnesium.",
          "description": "Badami mangoes, also known as Karnataka Alphonso, are a variety of mango grown in India. They are known for their sweet taste, creamy texture, and smooth, velvety flesh. Badami mangoes are small to medium in size, with pale yellow skin and attractive yellow or orange flesh. They are also rich in vitamins A and C, as well as iron, folate, and magnesium.",
          "Packaging": "1 Box Containing 5 KG Of Mangoes",
          "Package": "Strip",
          "Quantity": 1,
          "Product Form": "Tablet",
          "MRP": 450,
          "discount_percent": "Get 20% OFF",
          "bought": "3,601 people bought this recently",
          "storage": "Store below 30C",
          "country_of_origin": "India",
          "for_sale": "ADD TO CART",
          
        },
        {
          "Id": 5,
          "name": "Kesar Mango",
          "imgurl1": "https://i.postimg.cc/qqnWLJpp/6.jpg",
          "imgurl2": "https://i.postimg.cc/qqnWLJpp/6.jpg",
          "stock": "In Stock",
          "introduction": "Kesar mangoes, also known as Gir Kesar mangoes, are a variety of mango that originated in western India's Gujarat region. The name comes from the Hindi word kesar, which means saffron, because the fruit is similar in color to saffron. Kesar mangoes are small to medium in size, oval-oblong in shape, and have a bright orange color with a pinkish-red blush when ripe. They are known for their sweet, rich, and succulent taste, as well as their enticing aroma that lingers on your fingers. Kesar mangoes are also fiberless and full of spice and terpenes.",
          "description": "Kesar mangoes are considered to have a more subtle sweetness than Alphonso mangoes, which are bright orange, sweeter, and have a richer flavor. Kesar mangoes can be eaten as a snack or added to dishes, and are also celebrated for their unique texture and numerous health benefits. Kesar mangoes are grown in India, Pakistan, and some parts of Africa. In Florida, they are a mid-season mango that ripen from late June through July. They perform well in the climate of south Florida, but the flowers are very prone to powdery mildew",
          "Packaging": "1 Box Containing 5 KG Of Mangoes",
          "Package": "Strip",
          "Quantity": 1,
          "Product Form": "Tablet",
          "MRP": 500,
          "discount_percent": "Get 20% OFF",
          "bought": "3,601 people bought this recently",
          "storage": "Store below 30C",
          "country_of_origin": "India",
          "for_sale": "ADD TO CART",
          
        },
        {
          "Id": 6,
          "name": "Langra Mangoes",
          "imgurl1": "https://i.postimg.cc/kgwzwhPR/4.jpg",
          "imgurl2": "https://i.postimg.cc/kgwzwhPR/4.jpg",
          "stock": "In Stock",
          "introduction": "The 'Langra' mango, also known as Benarasi Langra, is a mango cultivar first cultivated 250 to 300 years ago in Banaras, present-day Uttar Pradesh, India. Besides Uttar Pradesh, it is grown in Bihar, West Bengal, and Bangladesh. In parts of northern India and Bihar, it is also known as 'Malda Mango,' referencing the town of Malda in West Bengal and the Digha, Patna region in Patna district. Often referred to as the 'king of mangoes,' this cultivar retains a greenish tinge while ripening and is typically harvested from mid-June to late July. By 2006, it was gaining international popularity. The Langra mango is suitable for slicing and canning.",
          "description": "The 'Langra' mango, also known as Benarasi Langra, originated 250 to 300 years ago in Banaras, Uttar Pradesh, India. It is also cultivated in Bihar, West Bengal, and Bangladesh. In northern India and Bihar, it is called 'Malda Mango,' referencing Malda in West Bengal and the Digha, Patna region. Known as the 'king of mangoes,' the Langra mango retains a greenish tinge while ripening and is harvested from mid-June to late July. By 2006, it gained international popularity. This variety is ideal for slicing and canning.",
          "Packaging": "1 Box Containing 5 KG Of Mangoes",
          "Package": "Strip",
          "Quantity": 1,
          "Product Form": "Tablet",
          "MRP": 400,
          "discount_percent": "Get 20% OFF",
          "bought": "3,601 people bought this recently",
          "storage": "Store below 30C",
          "country_of_origin": "India",
          "for_sale": "ADD TO CART",
          
        },
      ];
    export default data;